language: ruby
cache: bundler
 
rvm:
  - 2.0.0
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
 
bundler_args: 
  --without development
 
branches:
  only:
    - master

addons:
  code_climate:
    repo_token: adf08323...
 
notifications:
  email:
    - web.guru.serbia@gmail.com
