language: ruby
cache: bundler
 
rvm:
  - 2.0.0
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: 'bundle exec rake spec'
 
bundler_args: --without development
 
branches:
  only:
    - master
 
notifications:
  email:
    - web.guru.serbia@gmail.com
